import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { JsonStore } from '../src/data/store.js';
import { createApplication } from '../src/server.js';
import { createDefaultCharacter, resolveMechanics, sanitizeAiDirectives } from '../src/game/engine.js';
import { CLASSES, chooseClass, grantXp, allocate, train, makeGeneratedItem } from '../src/game/catalog.js';
import { initializeIsekai, progressWorld, publicAtlas } from '../src/game/world.js';
import { advanceCampaignMemory, memoryContext } from '../src/game/memory.js';
import { buildNarrativePrompt } from '../src/game/narrative.js';
import { SecretVault } from '../src/core/secret-vault.js';
import { client, register, testApplication } from './helpers.js';
const valid=ctx=>({narrative:`A cena continua no turno ${ctx.turn.number}.`,summary:'O grupo avançou.',provider:'mock',character_updates:[],events:[],world_updates:{},memory_updates:{facts_add:[],facts_close:[]}});
function unit(text,extra={}){const c=createDefaultCharacter('u','c','Lina');return {campaign:{settings:{allowPvp:false,...extra},world:{location:'Estrada',entities:[{id:'enemy',name:'Goblin',hp:100,maxHp:100,status:'ALIVE',attributes:{speed:8,resistance:8}}],npcs:[],quests:[]}},characters:[c],actions:[{id:'action',characterId:c.id,text,submittedAt:'2026-01-01'}],turnNumber:1,random:()=>.5};}
async function demo(t,opts={}){const app=await testApplication(opts);t.after(app.cleanup);const owner=client(app.base);const user=(await register(owner,201)).data.user;await owner.request('/api/profile/ai',{method:'PATCH',body:{provider:'gemini',apiKey:'fake-key-for-offline-test'}});const created=await owner.request('/api/demo',{method:'POST'});assert.equal(created.status,201);return {app,owner,user,id:created.data.campaign.id};}

test('catálogo concede habilidades das vinte e quatro classes sem poderes livres',()=>{assert.equal(CLASSES.length,24);for(const cls of CLASSES){const c=createDefaultCharacter('u','c','Nome');chooseClass(c,cls.id);assert.equal(c.powers.length,1);assert.equal(c.powers[0].classId,cls.id);assert.ok(c.powers[0].cost[c.powers[0].resource]>0);assert.equal(c.powers[0].unlockLevel,1);}});
test('progressão, desbloqueio, treinamento e alocação são autoritativos',()=>{const c=createDefaultCharacter('u','c','Nome');chooseClass(c,'mage');assert.equal(grantXp(c,300),2);assert.equal(c.level,3);assert.equal(c.powers.length,2);assert.equal(c.attributePoints,6);const before=c.attributes.magic;allocate(c,{magic:3,resistance:3});assert.equal(c.attributes.magic,before+3);assert.equal(c.attributePoints,0);assert.throws(()=>allocate(c,{magic:1}));assert.throws(()=>allocate(c,{magic:-1}));train(c,c.powers[0].id);assert.equal(c.powers[0].level,2);});
test('poder inexistente não causa dano ou gasto',()=>{for(const text of ['Uso parar o tempo e ataco Goblin.','Uso magia de fogo contra Goblin.','Uso minha habilidade de teleporte infinito.']){const ctx=unit(text);const r=resolveMechanics(ctx);assert.equal(r.outcomes[0].success,false);assert.equal(r.world.entities[0].hp,100);assert.equal(r.characters[0].resources.mana,50);}});
test('recarga impede repetição e custo é cobrado uma vez',()=>{const ctx=unit('Uso Golpe Determinado contra Goblin');let r=resolveMechanics(ctx);assert.equal(r.characters[0].resources.stamina,42);assert.equal(r.characters[0].cooldowns['warrior-1'],2);r=resolveMechanics({...ctx,characters:r.characters,world:r.world,turnNumber:2});assert.equal(r.outcomes[0].success,false);assert.equal(r.characters[0].resources.stamina,42);});
test('PvP desligado bloqueia dano e custo; ligado usa as mesmas regras',()=>{const ctx=unit('Ataco Bruno.');const b=createDefaultCharacter('v','c','Bruno');ctx.characters.push(b);let r=resolveMechanics(ctx);assert.equal(r.characters[1].resources.hp,100);assert.equal(r.characters[0].resources.stamina,50);ctx.campaign.settings.allowPvp=true;r=resolveMechanics(ctx);assert.ok(r.characters[1].resources.hp<100);assert.equal(r.characters[0].resources.stamina,45);});
test('dados do servidor registram sucesso, falha crítica e crítico',()=>{for(const [random,die,success]of [[()=>0,1,false],[()=>.65,14,true],[()=>.999,20,true]]){const r=resolveMechanics({...unit('Ataco Goblin',{experimentalDice:true}),random});const roll=r.events.find(e=>e.type==='DICE_ROLLED').data;assert.equal(roll.die,die);assert.equal(roll.success,success);assert.equal(roll.total,roll.die+roll.bonus);}});
test('NPC fora da cena não ganha relações ou conhecimento por menção',()=>{const ctx=unit('Converso com Eira.');ctx.campaign.world.npcs=[{id:'eira',name:'Eira',location:'Outra cidade',relationships:{}}];const r=resolveMechanics(ctx);assert.deepEqual(r.world.npcs[0].relationships,{});});
test('mundo oculta nós desconhecidos e exige viagem consensual conectada',()=>{const world={location:'Estrada',npcs:[],quests:[],ecosystem:{}};initializeIsekai(world,'arrival');assert.equal(publicAtlas(world).nodes.some(n=>n.id==='ruins'),false);const actors=[1,2,3,4].map(i=>({id:String(i),status:'ALIVE'}));const actions=actors.map(c=>({characterId:c.id,text:'Viajo para Vila de Aurora.'}));progressWorld(world,actors,actions.slice(0,3),[],1);assert.equal(world.atlas.current,'crossroads');progressWorld(world,actors,actions,[],2);assert.equal(world.atlas.current,'village');assert.equal(publicAtlas(world).nodes.some(n=>n.id==='guild'),true);});
test('introdução possui diálogo divino e travessia por votos persistentes',()=>{const world={location:'Estrada',npcs:[],quests:[],ecosystem:{}};initializeIsekai(world,'origin');const actors=[1,2,3,4].map(i=>({id:String(i),status:'ALIVE'}));const actions=actors.map(c=>({characterId:c.id,text:'Aceito a travessia.'}));progressWorld(world,actors,actions,[],1);assert.equal(world.introduction.phase,'divine');assert.equal(world.introduction.completed,false);progressWorld(world,actors,actions,[],2);assert.equal(world.introduction.completed,true);});
test('memória mantém fatos antigos e recupera NPC relevante após 300 turnos',()=>{const c={description:'Teste',settings:{},world:{location:'Ponte',npcs:[{id:'e',name:'Eira',location:'Ponte',personality:'Reservada',knowledge:['Só a promessa feita a ela.']},{id:'x',name:'Ausente',location:'Longe',personality:'Segredo'}]}};for(let i=1;i<=300;i++)advanceCampaignMemory(c,{turnNumber:i,summary:`Evento ${i}`,actions:[{characterId:'u',text:i===1?'Converso com Eira: prometo recuperar o medalhão.':'Converso com Eira.'}],memoryUpdates:{factsAdd:[{text:`Fato ${i}`,importance:2}]}});assert.equal(c.memory.facts.length,300);assert.ok(c.memory.archive.length>0);const context=memoryContext(c,[{text:'Pergunto a Eira sobre o medalhão.'}]);assert.equal(context.private_npc_memory.length,1);assert.match(JSON.stringify(context),/medalhão/);assert.ok(JSON.stringify(context).length<20000);assert.equal(c.memory.npcMemories.x.interactions.length,0);});
test('saída da IA jamais modifica HP, inventário ou local',()=>{for(const raw of [{narrative:'Texto',character_updates:{invalid:true},world_updates:{location:'Lua'},events:[null]}, {narrative:'Texto',character_updates:[{hp_delta:999}],memory_updates:{facts_add:[null,{text:'ok'}]}}]){const d=sanitizeAiDirectives(raw);assert.deepEqual(d.characterUpdates,[]);assert.deepEqual(d.worldUpdates,{});assert.deepEqual(d.events,[]);}assert.equal(sanitizeAiDirectives({narrative:{evil:1}}).narrative,'');});
test('falha de disco não publica o draft em memória',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'germinal-disk-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const store=await new JsonStore(path.join(dir,'db.json')).init();store.filePath=path.join(dir,'missing','db.json');await assert.rejects(store.mutate(s=>s.users.push({id:'ghost'})));assert.equal(store.read(s=>s.users.length),0);});
test('banco corrompido e cofre inválido falham sem sobrescrever',async t=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'germinal-corrupt-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'db.json');await fs.writeFile(file,'broken');await assert.rejects(new JsonStore(file).init());assert.equal(await fs.readFile(file,'utf8'),'broken');const key=path.join(dir,'server.key');await fs.writeFile(key,'broken');await assert.rejects(SecretVault.open(key));assert.equal(await fs.readFile(key,'utf8'),'broken');});
for(const failure of ['quota','timeout','invalid','auth'])test(`turno atômico com ${failure}, troca API e retries concorrentes`,async t=>{
 let failing=true,calls=0;const recorded=[];const narrator={availability:()=>({gemini:true,openai:true}),generate:async ctx=>{calls++;recorded.push(structuredClone(ctx.mechanics));if(failing){if(failure==='invalid')return {narrative:null};throw new Error({quota:'429 quota',timeout:'timeout',auth:'401 key'}[failure]);}await new Promise(r=>setTimeout(r,20));return valid(ctx);}};
 const {app,owner,id}=await demo(t,{narrative:narrator});const before=app.store.read(s=>s.characters.filter(c=>c.campaignId===id));const sent=await owner.request(`/api/campaigns/${id}/action`,{method:'POST',body:{text:'Ataco Goblin Batedor.'}});assert.equal(sent.data.resolved,false);let view=(await owner.request(`/api/campaigns/${id}/state`)).data;assert.equal(view.turn.status,'WAITING_FOR_AI');assert.deepEqual(app.store.read(s=>s.characters.filter(c=>c.campaignId===id)),before);const staged=app.store.read(s=>s.turns.find(t=>t.id===view.turn.id).staged);assert.ok(staged);assert.equal(JSON.stringify(view).includes('snapshot'),false);
 const backup=(await owner.request(`/api/campaigns/${id}/export`)).data;assert.equal(JSON.stringify(backup).includes('staged'),false);
 const setting=await owner.request(`/api/campaigns/${id}/settings`,{method:'PATCH',body:{aiProvider:'openai',aiApiKey:'new-key-for-test-only',aiModel:'test'}});assert.equal(setting.status,200);failing=false;
 const retries=await Promise.all([owner.request(`/api/campaigns/${id}/retry-ai`,{method:'POST'}),owner.request(`/api/campaigns/${id}/retry-ai`,{method:'POST'})]);assert.equal(retries.filter(r=>r.status===200).length,1);assert.equal(calls,2);assert.deepEqual(recorded[0],recorded[1]);view=(await owner.request(`/api/campaigns/${id}/state`)).data;assert.equal(view.turn.number,2);assert.equal((await owner.request(`/api/campaigns/${id}/history`)).data.history.length,1);
});
test('ficha e configurações bloqueadas após primeira ação, mesmo com pausa',async t=>{const {app,owner,id}=await demo(t);await app.store.mutate(s=>{const c=s.campaigns.find(c=>c.id===id);c.isDemo=false;});await owner.request(`/api/campaigns/${id}/action`,{method:'POST',body:{text:'Observo a estrada.'}});await owner.request(`/api/campaigns/${id}/pause`,{method:'POST'});assert.equal((await owner.request(`/api/campaigns/${id}/character`,{method:'PATCH',body:{identity:{name:'Mudança'}}})).status,409);assert.equal((await owner.request(`/api/campaigns/${id}/settings`,{method:'PATCH',body:{allowPvp:true}})).status,409);assert.equal((await owner.request(`/api/campaigns/${id}/character-operation`,{method:'POST',body:{operation:'allocate',allocation:{strength:1}}})).status,409);});
test('reinício preserva sessão e cálculo e não chama IA automaticamente',async t=>{const {app,owner,id}=await demo(t);const user=app.service.sessionUser(owner.cookie.split('=')[1]);await app.store.mutate(s=>{const c=s.campaigns.find(c=>c.id===id);const turn=s.turns.find(t=>t.id===c.currentTurnId);turn.status='PROCESSING';turn.staged={test:'preserved'};});await app.stop();let calls=0;const restarted=await createApplication({rootDir:path.resolve('.'),dataFile:app.config.dataFile,vaultKeyFile:app.config.vaultKeyFile,port:0,host:'127.0.0.1',narrative:{availability:()=>({}),generate:()=>{calls++;}}});t.after(()=>restarted.stop());await restarted.start();const restored=restarted.service.campaignState(id,user.id);assert.equal(restored.turn.status,'WAITING_FOR_AI');assert.deepEqual(restarted.store.read(s=>s.turns.find(t=>t.id===restored.turn.id).staged),{test:'preserved'});assert.equal(calls,0);assert.equal(restarted.service.sessionUser(owner.cookie.split('=')[1]).id,user.id);});
test('dev tools não disponíveis em produção nem para visitantes',async t=>{const {owner,id}=await demo(t);assert.equal((await owner.request(`/api/campaigns/${id}/dev-operation`,{method:'POST',body:{operation:'xp'}})).status,404);const d=await demo(t,{devTools:true});assert.equal((await d.owner.request(`/api/campaigns/${d.id}/dev-operation`,{method:'POST',body:{operation:'xp'}})).status,200);const other=client(d.app.base);await register(other,202);assert.equal((await other.request(`/api/campaigns/${d.id}/dev-operation`,{method:'POST',body:{operation:'xp'}})).status,403);});
test('chave testada no servidor e nunca devolvida em resposta',async t=>{const {owner}=await demo(t);const result=await owner.request('/api/profile/ai/test',{method:'POST',body:{provider:'gemini'}});assert.equal(result.status,200);assert.equal(result.data.ok,true);assert.equal(JSON.stringify(result.data).includes('fake-key'),false);});
test('20 turnos reais de serviço consolidam progresso sem duplicação',async t=>{const {app,owner,id}=await demo(t);for(let i=1;i<=20;i++){const result=await owner.request(`/api/campaigns/${id}/action`,{method:'POST',body:{text:'Descanso e observo o ambiente.'}});assert.equal(result.status,200);assert.equal(result.data.resolved,true);}const view=(await owner.request(`/api/campaigns/${id}/state`)).data;assert.equal(view.turn.number,21);assert.ok(view.character.level>=2);const db=new JsonStore(app.config.dataFile);await db.init();assert.equal(db.read(s=>s.turns.filter(t=>t.campaignId===id&&t.status==='RESOLVED').length),20);});

test('teste de IA aceita chave digitada sem salvá-la',async t=>{
  let received='';
  const app=await testApplication({narrative:{availability:()=>({}),generate:async(_context,credential)=>{received=credential?.apiKey||'';return {narrative:'Conexão confirmada.',summary:'ok',provider:'gemini'};}}});
  t.after(app.cleanup);
  const browser=client(app.base);await register(browser,909);
  let profile=(await browser.request('/api/profile')).data;assert.equal(profile.aiCredentials.gemini.configured,false);
  const tested=await browser.request('/api/profile/ai/test',{method:'POST',body:{provider:'gemini',apiKey:'chave-temporaria-123456',model:'gemini-3.8-flash'}});
  assert.equal(tested.status,200);assert.equal(tested.data.testedUnsavedKey,true);assert.equal(received,'chave-temporaria-123456');
  profile=(await browser.request('/api/profile')).data;assert.equal(profile.aiCredentials.gemini.configured,false);
});

test('chave salva pode ser substituída e excluída sem apagar dados do usuário',async t=>{
  const app=await testApplication();t.after(app.cleanup);const browser=client(app.base);await register(browser,910);
  assert.equal((await browser.request('/api/profile/ai',{method:'PATCH',body:{provider:'gemini',apiKey:'primeira-chave-123456',model:'gemini-3.8-flash'}})).status,200);
  assert.equal((await browser.request('/api/profile/ai',{method:'PATCH',body:{provider:'gemini',apiKey:'segunda-chave-654321',model:'gemini-3.8-flash'}})).status,200);
  let profile=(await browser.request('/api/profile')).data;assert.equal(profile.aiCredentials.gemini.configured,true);assert.equal(JSON.stringify(profile).includes('segunda-chave'),false);
  assert.equal((await browser.request('/api/profile/ai',{method:'PATCH',body:{provider:'gemini',remove:true}})).status,200);
  profile=(await browser.request('/api/profile')).data;assert.equal(profile.aiCredentials.gemini.configured,false);
});


test('item criado por IA é sanitizado e balanceado pelo servidor',()=>{
  const item=makeGeneratedItem({
    name:'Espada do Fim de Tudo',icon:'⚔',description:'Uma lâmina lendária criada pelo Host.',type:'WEAPON',rarity:'LEGENDARY',slot:'weapon',value:999999,weight:2,quantity:99,requirements:{level:50},effects:[{type:'HEAL',value:999}],attributes:{attack:999,defense:999,strength:999}
  },{request:'espada lendária',level:1});
  assert.equal(item.type,'WEAPON');assert.equal(item.quantity,20);assert.equal(item.value,10000);assert.equal(item.requirements.level,6);assert.deepEqual(item.effects,[]);
  assert.ok(Object.values(item.attributes).every(v=>v<=2));assert.ok(Object.values(item.attributes).reduce((a,b)=>a+b,0)<=4);assert.equal(item.metadata.source,'host-ai');
});

test('Host descreve item em texto e IA entrega item balanceado direto na mochila',async t=>{
  let requestSeen='';
  const narrator={availability:()=>({gemini:true}),generate:async ctx=>valid(ctx),generateItem:async ctx=>{requestSeen=ctx.request;return {name:'Lâmina da Aurora',icon:'⚔',description:'Espada de prata que reflete a primeira luz do vale.',type:'WEAPON',rarity:'LEGENDARY',slot:'weapon',value:900,weight:2.1,quantity:1,requirements:{level:1},attributes:{attack:999,speed:999},effects:[]};}};
  const {app,owner,id}=await demo(t,{narrative:narrator});
  assert.equal((await owner.request(`/api/campaigns/${id}/pause`,{method:'POST'})).status,200);
  const before=(await owner.request(`/api/campaigns/${id}/state`)).data;const characterId=before.character.id;
  const granted=await owner.request(`/api/campaigns/${id}/admin-operation`,{method:'POST',body:{operation:'grant-ai-item',characterId,itemId:'uma espada lendária ligada à aurora',quantity:2,reason:'Recompensa narrativa'}});
  assert.equal(granted.status,200);assert.equal(granted.data.item.name,'Lâmina da Aurora');assert.equal(granted.data.item.quantity,2);assert.equal(requestSeen,'uma espada lendária ligada à aurora');
  const after=(await owner.request(`/api/campaigns/${id}/state`)).data;const item=after.character.inventory.find(i=>i.name==='Lâmina da Aurora');assert.ok(item);assert.equal(item.quantity,2);assert.ok(Object.values(item.attributes).reduce((a,b)=>a+b,0)<=4);
});
